### ISSUE TITLE
.NET Core Support?

### ISSUE THREAD

**Issue by nightblade9** [GameAnalytics/GA-SDK-C-SHARP#43]
Hi,

Are there any plans to make a .NET Core version of this SDK client? My game is in .NET Core and I don't think the Mono/UWP versions will work.

**Comment by the1schwartz** [comment]
Thanks for the request. I will look into getting support for .Net Core for this SDK.

**Comment by the1schwartz** [comment]
Hi again,

I have updated the SDK and it should support .Net Core (3.0) now. It can be installed via nuget as described here: https://gameanalytics.com/docs/item/c-sharp-sdk#installation-net-core
