### ISSUE TITLE
IL2CPP Requirement for Unity

### ISSUE THREAD

**Issue by nbelisle11** [GameAnalytics/GA-SDK-C-SHARP#44]
In your documentation it says `When building for desktop platforms (Windows/Mac/Linux) you now need to pick ILL2CPP as scripting backend in Unity.`

Can you help me understand this requirement a bit more and why this is the case? I see that the SDK is written directly in C# with Mono support so why wouldn't this work on a standard mono build? 

Does this also mean I need to perform a full build in order to properly test this system as playing this in the editor will not be IL2CPP compliant? This adds quite a bit of overhead to the testing pipeline as game builds are time consuming (IL2CPP builds even more so).

This requirement presents an issue for us as we're working through playtesting and demos on many different platforms and IL2CPP must be built on each target OS directly. So we'll need 3 separate machines running unity on Windows, MacOS, and Linux to build IL2CPP for each. Thanks.

**Comment by the1schwartz** [comment]
Last I time I tested it only seemed to work for IL2CPP but it is also a while since I did a full test for all the platforms so maybe it will actually for work fine for Mono backend as well. Feel free to test if it actually works with Mono backend. I will try to test as well during next week if we can remove this requirement. Thanks.

**Comment by the1schwartz** [comment]
Hi again,

I just tested for all desktop platforms and they build fine with Mono scripting backend. So it is not required to only use IL2CPP scripting backend, you can also you Mono. I will remove this from the documentation page. Thanks again.

**Comment by nbelisle11** [comment]
I believe this was sorted here
https://github.com/GameAnalytics/GA-SDK-C-SHARP/issues/44#issuecomment-636400697

**Comment by nbelisle11** [comment]
Sorry wrong thread.
