### ISSUE TITLE
Build failure when GameAnalytics added with heyzap SDK

### ISSUE THREAD

**Issue by pro404** [GameAnalytics/GA-SDK-C-SHARP#9]
Hi,

Unity Android project is not building when I add GameAnalytics SDK and HeyZap SDK in my project.
You can find the error log in following link.

http://pastebin.com/d9Ukbcre

Kind Regards

**Comment by the1schwartz** [comment]
Hi,

Could you please submit a support ticket to support@gameanalytics.com instead and a support agent help you with this issue.

Thanks,
Martin
Lead SDK Developer @ GameAnalytics
